### ISSUE TITLE
Error in admin

### ISSUE THREAD

**Issue by danielchicote** [outeredge/edge-magento-module-printproof#5]
Hello, im trying your module and i found this error in the admin when i open an order and lists the printing orders:

Fatal error: Class 'Mage_Edge_Helper_Image' not found in C:\xampp\htdocs\magento\app\Mage.php on line 547

Where is defined this class?

**Comment by vseager** [comment]
At the moment this module relies on our image helper that exists in edge-magento-module-base

**Comment by vseager** [comment]
I've updated composer to require our base module now.
